# Use an official Python 3.11 base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

ENV TRANSFORMERS_CACHE=/tmp
ENV HF_HOME=/tmp

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the FastAPI application code
COPY . .

# Expose port 8000 for the FastAPI app
EXPOSE 8000

# Run the FastAPI app with uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]